services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: ims
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
